try {
    console.log(dontexist);
} catch (err){
    console.log("Don't exists");
    console.log(err); // to see the error
}